import type { AssessmentQuestionId } from "@/components/assessment/AssessmentTypes";

export const HABIT_RECOMMENDATIONS: Partial<Record<AssessmentQuestionId, string>> = {
  fruitsVegServings: "Eat more fruits and vegetables each day.",
  processedMeals: "Reduce fast food, takeout, and highly processed packaged meals.",
  addedSugar: "Cut back on sugary drinks and foods with added sugar.",
  homeCookedMeals: "Cook more meals at home using fresh ingredients.",
  hydrationChoice: "Choose water, sparkling water, or unsweet tea most of the day.",
  moderateActivity: "Add more brisk walking, hiking, or cycling into your week.",
  strengthDays: "Schedule at least two strength-focused sessions each week.",
  sedentaryTime: "Break up sitting by standing, stretching, and moving more often.",
  lifestyleMovement: "Layer natural movement into errands, chores, and daily routines.",
  sleepHours: "Protect 7–8 hours of sleep most nights.",
  wakeRested: "Aim to wake feeling rested by improving sleep routines.",
  sleepConsistency: "Keep bed and wake times within a consistent window.",
  meaningfulTime: "Spend regular, meaningful time with friends or family.",
  sharedMeals: "Share more meals at a table with others.",
  screenFreeMeals: "Enjoy meals without screens so you can connect and slow down.",
  communityBelonging: "Engage with a group, class, or gathering that feels supportive.",
  senseOfPurpose: "Clarify what gives you meaning and align habits with that purpose.",
  meaningfulActivities: "Make time each week for activities that feel meaningful.",
  contributionFrequency: "Offer your time or skills to help someone each week.",
  overwhelmFrequency: "Use stress-reduction practices before overwhelm sets in.",
  outdoorQuietTime: "Spend more time outdoors or in quiet reflection to reset.",
  alcohol: "Reduce alcohol intake to a lighter, more sustainable level.",
  nicotine: "Eliminate nicotine or maintain a nicotine-free routine.",
  chronicCondition: "Work with your care team to manage chronic conditions proactively.",
  preventiveCare: "Schedule routine preventive visits so issues are caught early.",
  grandparents85: "Adopt habits that compensate for limited family longevity.",
};
