import type {
  AssessmentOption,
  AssessmentQuestion,
  AssessmentQuestionId,
  AssessmentSectionConfig,
  OptionalMarkerKey,
} from "@/components/assessment/AssessmentTypes";

export const ASSESSMENT_SECTIONS: AssessmentSectionConfig[] = [
  {
    id: "startingPoint",
    title: "Your Starting Point",
    description: "A few basics to personalize your results.",
  },
  {
    id: "food",
    title: "Food",
    description: "Everyday eating habits that shape long-term health.",
  },
  {
    id: "movement",
    title: "Movement",
    description: "How often your body moves, works, and stays strong.",
  },
  {
    id: "sleep",
    title: "Sleep",
    description: "Rest, rhythm, and recovery.",
  },
  {
    id: "connection",
    title: "Connection",
    description: "Relationships and shared experiences that support longevity.",
  },
  {
    id: "purpose",
    title: "Purpose",
    description: "Meaning, direction, and contribution.",
  },
  {
    id: "stressRegulation",
    title: "Stress Regulation",
    description: "How you recover, reset, and protect your wellbeing.",
  },
  {
    id: "healthContext",
    title: "Health Context",
    description: "Background health factors that add context to your current profile.",
  },
];

const OPTION_LABELS: Partial<Record<AssessmentQuestionId | OptionalMarkerKey, AssessmentOption[]>> = {
  fruitsVegServings: [
    { value: "underOne", label: "Less than 1 serving per day" },
    { value: "oneToTwo", label: "1–2 servings per day" },
    { value: "threeToFour", label: "3–4 servings per day" },
    { value: "fivePlus", label: "5+ servings per day" },
  ],
  processedMeals: [
    { value: "mostMeals", label: "Most meals" },
    { value: "onePerDay", label: "About once per day" },
    { value: "fewPerWeek", label: "A few times per week" },
    { value: "rarely", label: "Rarely" },
  ],
  addedSugar: [
    { value: "multiDaily", label: "Several times per day" },
    { value: "daily", label: "Once per day" },
    { value: "fewPerWeek", label: "A few times per week" },
    { value: "rarely", label: "Rarely or never" },
  ],
  homeCookedMeals: [
    { value: "underTwo", label: "0–2 meals per week" },
    { value: "threeToFour", label: "3–4 meals per week" },
    { value: "fiveToSix", label: "5–6 meals per week" },
    { value: "mostDays", label: "Most meals each week" },
  ],
  hydrationChoice: [
    { value: "mostlySugary", label: "Sugary drinks most of the day" },
    { value: "sweetenedMix", label: "Mix of sweetened drinks and water" },
    { value: "waterPlus", label: "Mostly water or unsweet tea with occasional flavored drinks" },
    { value: "mostlyWater", label: "Nearly all water, unsweet tea, or sparkling water" },
  ],
  moderateActivity: [
    { value: "lessThanWeekly", label: "Less than once per week" },
    { value: "oneToTwoPerWeek", label: "1–2 times per week" },
    { value: "threeToFourPerWeek", label: "3–4 times per week" },
    { value: "mostDays", label: "Most days" },
  ],
  strengthDays: [
    { value: "none", label: "Rarely" },
    { value: "oneDay", label: "1 day per week" },
    { value: "twoDays", label: "2 days per week" },
    { value: "threePlusDays", label: "3+ days per week" },
  ],
  sedentaryTime: [
    { value: "overTenHours", label: "10+ hours sitting per day" },
    { value: "sevenToTenHours", label: "7–10 hours sitting per day" },
    { value: "fourToSixHours", label: "4–6 hours sitting per day" },
    { value: "underFourHours", label: "Less than 4 hours sitting per day" },
  ],
  lifestyleMovement: [
    { value: "mostlySeated", label: "Mostly seated outside workouts" },
    { value: "mixed", label: "Mix of sitting and moving" },
    { value: "onFeet", label: "On your feet or walking much of the day" },
    { value: "activeAllDay", label: "Very active lifestyle (walking, chores, caregiving)" },
  ],
  sleepHours: [
    { value: "underSix", label: "Under 6 hours" },
    { value: "sixToSeven", label: "6–7 hours" },
    { value: "sevenToEight", label: "7–8 hours" },
    { value: "overEight", label: "Over 8 hours with good quality" },
  ],
  wakeRested: [
    { value: "rarelyRested", label: "Rarely" },
    { value: "sometimesRested", label: "Sometimes" },
    { value: "mostMornings", label: "Most mornings" },
    { value: "almostAlwaysRested", label: "Almost always" },
  ],
  sleepConsistency: [
    { value: "inconsistent", label: "Bed/wake times vary by 3+ hours" },
    { value: "somewhatConsistent", label: "Within a 2-hour window" },
    { value: "mostlyConsistent", label: "Within a 1-hour window" },
    { value: "veryConsistent", label: "Within the same 30-minute window" },
  ],
  meaningfulTime: [
    { value: "rarely", label: "Rarely" },
    { value: "fewTimesPerMonth", label: "A few times per month" },
    { value: "weekly", label: "Weekly" },
    { value: "severalPerWeek", label: "Several times per week" },
  ],
  sharedMeals: [
    { value: "rarely", label: "Rarely" },
    { value: "fewTimesPerMonth", label: "A few times per month" },
    { value: "weekly", label: "Weekly" },
    { value: "mostDays", label: "Most days" },
  ],
  screenFreeMeals: [
    { value: "almostAlwaysWithScreens", label: "Almost always with screens" },
    { value: "oftenWithScreens", label: "Often with screens" },
    { value: "sometimesWithoutScreens", label: "Sometimes screen-free" },
    { value: "usuallyScreenFree", label: "Usually screen-free" },
  ],
  communityBelonging: [
    { value: "disconnected", label: "I don’t feel connected" },
    { value: "someBelonging", label: "Some belonging" },
    { value: "solidBelonging", label: "Solid sense of belonging" },
    { value: "deepBelonging", label: "Deep belonging and participation" },
  ],
  senseOfPurpose: [
    { value: "noClearPurpose", label: "No clear purpose" },
    { value: "emergingPurpose", label: "Some direction" },
    { value: "clearPurpose", label: "Clear sense of purpose" },
    { value: "anchoredPurpose", label: "Purpose drives most decisions" },
  ],
  meaningfulActivities: [
    { value: "lessThanMonthly", label: "Less than monthly" },
    { value: "monthly", label: "Monthly" },
    { value: "weekly", label: "Weekly" },
    { value: "severalPerWeek", label: "Several times per week" },
  ],
  contributionFrequency: [
    { value: "rarely", label: "Rarely" },
    { value: "fewTimesPerYear", label: "A few times per year" },
    { value: "monthly", label: "Monthly" },
    { value: "weekly", label: "Weekly or more" },
  ],
  overwhelmFrequency: [
    { value: "almostDaily", label: "Almost daily" },
    { value: "fewTimesPerWeek", label: "A few times per week" },
    { value: "sometimes", label: "Sometimes" },
    { value: "rarely", label: "Rarely" },
  ],
  outdoorQuietTime: [
    { value: "rarely", label: "Rarely" },
    { value: "fewTimesPerMonth", label: "A few times per month" },
    { value: "weekly", label: "Weekly" },
    { value: "severalPerWeek", label: "Several times per week" },
  ],
  alcohol: [
    { value: "fifteenPlus", label: "15+ drinks per week" },
    { value: "eightToFourteen", label: "8–14 drinks per week" },
    { value: "oneToSeven", label: "1–7 drinks per week" },
    { value: "none", label: "No alcohol" },
  ],
  nicotine: [
    { value: "dailyUser", label: "Daily use" },
    { value: "occasionalUser", label: "Occasional use" },
    { value: "formerUser", label: "Former user" },
    { value: "neverUsed", label: "Never used" },
  ],
  chronicCondition: [
    { value: "yes", label: "Yes, currently managing one" },
    { value: "riskFactors", label: "I have risk factors or symptoms" },
    { value: "unsure", label: "Unsure / being evaluated" },
    { value: "no", label: "No chronic conditions" },
  ],
  preventiveCare: [
    { value: "never", label: "Rarely or never" },
    { value: "everyFiveYears", label: "About every 5 years" },
    { value: "everyTwoToThreeYears", label: "Every 2–3 years" },
    { value: "yearly", label: "Yearly" },
  ],
  grandparents85: [
    { value: "zero", label: "Zero" },
    { value: "one", label: "One" },
    { value: "two", label: "Two" },
    { value: "threeOrFour", label: "Three or four" },
  ],
  bloodPressure: [
    { value: "high", label: "High" },
    { value: "elevated", label: "Elevated" },
    { value: "normal", label: "Normal" },
    { value: "dontKnow", label: "I don’t know" },
  ],
  ldl: [
    { value: "high", label: "High" },
    { value: "borderline", label: "Borderline" },
    { value: "optimal", label: "Optimal" },
    { value: "dontKnow", label: "I don’t know" },
  ],
  fastingGlucose: [
    { value: "diabetes", label: "Diabetes range" },
    { value: "prediabetes", label: "Prediabetes range" },
    { value: "normal", label: "Normal" },
    { value: "dontKnow", label: "I don’t know" },
  ],
};

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  {
    id: "firstName",
    prompt: "First name",
    placeholder: "Your name",
    sectionId: "startingPoint",
    type: "text",
    required: true,
  },
  {
    id: "age",
    prompt: "What is your age?",
    sectionId: "startingPoint",
    type: "number",
    min: 18,
    max: 100,
    required: true,
  },
  {
    id: "sex",
    prompt: "What is your biological sex?",
    sectionId: "startingPoint",
    type: "singleSelect",
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
    ],
    required: true,
  },
  {
    id: "height",
    prompt: "What is your height?",
    sectionId: "startingPoint",
    type: "composite",
    compositeFields: [
      { id: "feet", label: "Feet", min: 3, max: 8, step: 1 },
      { id: "inches", label: "Inches", min: 0, max: 11, step: 1 },
    ],
    helperText: "Used to calculate body composition context.",
    required: true,
  },
  {
    id: "weight",
    prompt: "What is your weight (lbs)?",
    sectionId: "startingPoint",
    type: "number",
    min: 80,
    max: 450,
    helperText: "Used to calculate body composition context.",
    required: true,
  },
  {
    id: "fruitsVegServings",
    prompt: "How many servings of fruits and vegetables do you typically eat each day?",
    sectionId: "food",
    type: "singleSelect",
    options: OPTION_LABELS.fruitsVegServings,
  },
  {
    id: "processedMeals",
    prompt: "How often do you eat fast food, takeout, or highly processed packaged meals?",
    sectionId: "food",
    type: "singleSelect",
    options: OPTION_LABELS.processedMeals,
  },
  {
    id: "addedSugar",
    prompt: "How often do you consume foods or drinks with added sugar?",
    sectionId: "food",
    type: "singleSelect",
    options: OPTION_LABELS.addedSugar,
  },
  {
    id: "homeCookedMeals",
    prompt: "How many meals per week are cooked at home using fresh ingredients?",
    sectionId: "food",
    type: "singleSelect",
    options: OPTION_LABELS.homeCookedMeals,
  },
  {
    id: "hydrationChoice",
    prompt: "What do you drink most throughout the day?",
    sectionId: "food",
    type: "singleSelect",
    options: OPTION_LABELS.hydrationChoice,
  },
  {
    id: "moderateActivity",
    prompt: "How often do you get at least 30 minutes of moderate activity (walking, hiking, cycling)?",
    sectionId: "movement",
    type: "singleSelect",
    options: OPTION_LABELS.moderateActivity,
  },
  {
    id: "strengthDays",
    prompt: "How many days per week do you challenge your muscles through lifting, carrying, or resistance work?",
    sectionId: "movement",
    type: "singleSelect",
    options: OPTION_LABELS.strengthDays,
  },
  {
    id: "sedentaryTime",
    prompt: "How many hours each day do you spend sitting?",
    sectionId: "movement",
    type: "singleSelect",
    options: OPTION_LABELS.sedentaryTime,
  },
  {
    id: "lifestyleMovement",
    prompt: "Outside of workouts, how would you describe your natural movement during a typical day?",
    sectionId: "movement",
    type: "singleSelect",
    options: OPTION_LABELS.lifestyleMovement,
  },
  {
    id: "sleepHours",
    prompt: "On most nights, how many hours of sleep do you get?",
    sectionId: "sleep",
    type: "singleSelect",
    options: OPTION_LABELS.sleepHours,
  },
  {
    id: "wakeRested",
    prompt: "How often do you wake feeling rested?",
    sectionId: "sleep",
    type: "singleSelect",
    options: OPTION_LABELS.wakeRested,
  },
  {
    id: "sleepConsistency",
    prompt: "How consistent are your bed and wake times?",
    sectionId: "sleep",
    type: "singleSelect",
    options: OPTION_LABELS.sleepConsistency,
  },
  {
    id: "meaningfulTime",
    prompt: "How often do you spend meaningful, in-person time with friends, family, or neighbors?",
    sectionId: "connection",
    type: "singleSelect",
    options: OPTION_LABELS.meaningfulTime,
  },
  {
    id: "sharedMeals",
    prompt: "How often do you share meals with other people?",
    sectionId: "connection",
    type: "singleSelect",
    options: OPTION_LABELS.sharedMeals,
  },
  {
    id: "screenFreeMeals",
    prompt: "How often are your meals screen-free?",
    sectionId: "connection",
    type: "singleSelect",
    options: OPTION_LABELS.screenFreeMeals,
  },
  {
    id: "communityBelonging",
    prompt: "How connected do you feel to a community or group that shares your values?",
    sectionId: "connection",
    type: "singleSelect",
    options: OPTION_LABELS.communityBelonging,
  },
  {
    id: "senseOfPurpose",
    prompt: "How clear is your current sense of purpose?",
    sectionId: "purpose",
    type: "singleSelect",
    options: OPTION_LABELS.senseOfPurpose,
  },
  {
    id: "meaningfulActivities",
    prompt: "How often do you spend time on activities that feel meaningful to you?",
    sectionId: "purpose",
    type: "singleSelect",
    options: OPTION_LABELS.meaningfulActivities,
  },
  {
    id: "contributionFrequency",
    prompt: "How often do you contribute your time or skills to help others?",
    sectionId: "purpose",
    type: "singleSelect",
    options: OPTION_LABELS.contributionFrequency,
  },
  {
    id: "overwhelmFrequency",
    prompt: "How often do you feel overwhelmed by stress?",
    sectionId: "stressRegulation",
    type: "singleSelect",
    options: OPTION_LABELS.overwhelmFrequency,
  },
  {
    id: "outdoorQuietTime",
    prompt: "How often do you spend time outdoors or in quiet spaces to calm your nervous system?",
    sectionId: "stressRegulation",
    type: "singleSelect",
    options: OPTION_LABELS.outdoorQuietTime,
  },
  {
    id: "alcohol",
    prompt: "How many alcoholic drinks do you typically consume per week?",
    sectionId: "healthContext",
    type: "singleSelect",
    options: OPTION_LABELS.alcohol,
  },
  {
    id: "nicotine",
    prompt: "What best describes your nicotine use?",
    sectionId: "healthContext",
    type: "singleSelect",
    options: OPTION_LABELS.nicotine,
  },
  {
    id: "chronicCondition",
    prompt: "Do you currently manage any chronic conditions (e.g., heart disease, diabetes)?",
    sectionId: "healthContext",
    type: "singleSelect",
    options: OPTION_LABELS.chronicCondition,
  },
  {
    id: "preventiveCare",
    prompt: "How often do you receive preventive medical check-ups?",
    sectionId: "healthContext",
    type: "singleSelect",
    options: OPTION_LABELS.preventiveCare,
  },
  {
    id: "grandparents85",
    prompt: "How many biological grandparents lived to age 85 or older?",
    sectionId: "healthContext",
    type: "singleSelect",
    options: OPTION_LABELS.grandparents85,
  },
];

export const TOTAL_QUESTION_COUNT = ASSESSMENT_QUESTIONS.length;

const OPTIONAL_MARKER_FIELDS: OptionalMarkerKey[] = ["bloodPressure", "ldl", "fastingGlucose"];

export const OPTIONAL_MARKER_QUESTIONS: AssessmentQuestion[] = OPTIONAL_MARKER_FIELDS.map((key) => ({
  id: key,
  prompt:
    key === "bloodPressure"
      ? "What is your typical blood pressure?"
      : key === "ldl"
        ? "What is your LDL cholesterol level?"
        : "What is your fasting blood glucose level?",
  sectionId: "healthContext",
  type: "singleSelect",
  options: OPTION_LABELS[key],
  helperText: "Select “I don’t know” if this isn’t available.",
}));
