import type {
  AssessmentOption,
  AssessmentQuestion,
  AssessmentQuestionId,
  AssessmentSectionConfig,
  OptionalMarkerKey,
} from "@/components/assessment/AssessmentTypes";

export const ASSESSMENT_SECTIONS: AssessmentSectionConfig[] = [
  {
    id: "basicHealth",
    title: "Basic Health",
    description: "A few essentials so we can personalize your baseline.",
  },
  {
    id: "food",
    title: "Food",
    description: "How you nourish your body each day.",
  },
  {
    id: "movement",
    title: "Movement",
    description: "Activity patterns that influence metabolic health.",
  },
  {
    id: "sleep",
    title: "Sleep",
    description: "Rest and nightly recovery habits.",
  },
  {
    id: "connection",
    title: "Connection",
    description: "Relationships that buffer stress and support longevity.",
  },
  {
    id: "purposeStress",
    title: "Purpose & Stress Regulation",
    description: "Mindset and mental wellbeing inputs.",
  },
  {
    id: "healthHabits",
    title: "Health & Habits",
    description: "Substances and overall health perceptions.",
  },
];

const OPTION_LABELS: Record<AssessmentQuestionId, AssessmentOption[]> = {
  fruitsVeg: [
    { value: "rarely", label: "Rarely" },
    { value: "severalTimesPerWeek", label: "Several times per week" },
    { value: "daily", label: "Daily" },
    { value: "fivePlusServings", label: "5+ servings per day" },
  ],
  processedFoods: [
    { value: "rarely", label: "Rarely" },
    { value: "severalTimesPerWeek", label: "Several times per week" },
    { value: "daily", label: "Daily" },
    { value: "multipleTimesPerDay", label: "Multiple times per day" },
  ].reverse(),
  sugarIntake: [
    { value: "severalTimesDaily", label: "Several times per day" },
    { value: "dailyTreat", label: "Daily treat" },
    { value: "fewTreatsPerWeek", label: "A few treats per week" },
    { value: "rarelyOrNone", label: "Rarely or none" },
  ],
  homePreparedMeals: [
    { value: "rarely", label: "Rarely" },
    { value: "oneToTwoPerWeek", label: "1–2 per week" },
    { value: "threeToFivePerWeek", label: "3–5 per week" },
    { value: "mostDays", label: "Most days" },
  ],
  cardio: [
    { value: "rarelyOrNever", label: "Rarely or never" },
    { value: "under150", label: "Under 150 minutes" },
    { value: "from150To300", label: "150–300 minutes" },
    { value: "over300", label: "300+ minutes" },
  ],
  strengthTraining: [
    { value: "rarelyOrNever", label: "Rarely or never" },
    { value: "lessThanOnceWeekly", label: "Less than once weekly" },
    { value: "oneToTwoPerWeek", label: "1–2 sessions per week" },
    { value: "moreThanTwoPerWeek", label: "3+ sessions per week" },
  ],
  dailyMovement: [
    { value: "mostlySitting", label: "Mostly sitting" },
    { value: "someMovement", label: "Some movement" },
    { value: "frequentlyMoving", label: "Frequently moving" },
    { value: "veryActive", label: "Very active" },
  ],
  fitnessLevel: [
    { value: "poor", label: "Poor" },
    { value: "moderate", label: "Moderate" },
    { value: "good", label: "Good" },
    { value: "excellent", label: "Excellent" },
  ],
  sleepDuration: [
    { value: "rarely", label: "Rarely" },
    { value: "sometimes", label: "Sometimes" },
    { value: "often", label: "Often" },
    { value: "almostAlways", label: "Almost always" },
  ],
  sleepQuality: [
    { value: "fivePlusNights", label: "5+ nights per week" },
    { value: "threeToFourNights", label: "3–4 nights per week" },
    { value: "oneToTwoNights", label: "1–2 nights per week" },
    { value: "rarelyOrNever", label: "Rarely or never" },
  ],
  sleepSchedule: [
    { value: "rarely", label: "Rarely" },
    { value: "sometimes", label: "Sometimes" },
    { value: "often", label: "Often" },
    { value: "almostAlways", label: "Almost always" },
  ],
  timeWithOthers: [
    { value: "rarely", label: "Rarely" },
    { value: "fewTimesPerMonth", label: "Few times per month" },
    { value: "weekly", label: "Weekly" },
    { value: "daily", label: "Daily" },
  ],
  socialSupport: [
    { value: "notSupportive", label: "Not supportive" },
    { value: "slightlySupportive", label: "Slightly supportive" },
    { value: "fairlySupportive", label: "Fairly supportive" },
    { value: "verySupportive", label: "Very supportive" },
  ],
  sharedMeals: [
    { value: "rarely", label: "Rarely" },
    { value: "fewTimesPerMonth", label: "Few times per month" },
    { value: "weekly", label: "Weekly" },
    { value: "mostDays", label: "Most days" },
  ],
  screenFreeMeals: [
    { value: "almostAlwaysWithScreens", label: "Almost always with screens" },
    { value: "oftenWithScreens", label: "Often with screens" },
    { value: "sometimesWithoutScreens", label: "Sometimes without screens" },
    { value: "usuallyScreenFree", label: "Usually screen-free" },
  ],
  stressFrequency: [
    { value: "almostAllTheTime", label: "Almost all the time" },
    { value: "frequently", label: "Frequently" },
    { value: "occasionally", label: "Occasionally" },
    { value: "rarely", label: "Rarely" },
  ],
  mentalHealthImpact: [
    { value: "severely", label: "Severely" },
    { value: "moderately", label: "Moderately" },
    { value: "mildly", label: "Mildly" },
    { value: "notAtAll", label: "Not at all" },
  ],
  purpose: [
    { value: "noClearPurpose", label: "No clear purpose" },
    { value: "someDirection", label: "Some direction" },
    { value: "strongPurpose", label: "Strong sense of purpose" },
    { value: "deepSenseOfPurpose", label: "Deep sense of purpose" },
  ],
  alcohol: [
    { value: "fifteenPlus", label: "15+ drinks" },
    { value: "eightToFourteen", label: "8–14 drinks" },
    { value: "oneToSeven", label: "1–7 drinks" },
    { value: "none", label: "None" },
  ],
  nicotine: [
    { value: "dailyUser", label: "Daily user" },
    { value: "occasionalUser", label: "Occasional user" },
    { value: "formerUser", label: "Former user" },
    { value: "neverUsed", label: "Never used" },
  ],
  chronicDisease: [
    { value: "yes", label: "Yes" },
    { value: "riskFactors", label: "Risk factors present" },
    { value: "unsure", label: "Unsure" },
    { value: "no", label: "No" },
  ],
  selfRatedHealth: [
    { value: "poor", label: "Poor" },
    { value: "fair", label: "Fair" },
    { value: "good", label: "Good" },
    { value: "excellent", label: "Excellent" },
  ],
};

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  {
    id: "firstName",
    prompt: "First Name",
    placeholder: "Enter your first name",
    sectionId: "basicHealth",
    type: "text",
    required: true,
  },
  {
    id: "age",
    prompt: "Age",
    placeholder: "Enter your age",
    sectionId: "basicHealth",
    type: "number",
    min: 18,
    max: 100,
    required: true,
  },
  {
    id: "sex",
    prompt: "Biological Sex",
    sectionId: "basicHealth",
    type: "singleSelect",
    required: true,
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
    ],
  },
  {
    id: "height",
    prompt: "Height",
    sectionId: "basicHealth",
    type: "composite",
    required: true,
    compositeFields: [
      { id: "feet", label: "Feet", min: 3, max: 8, step: 1 },
      { id: "inches", label: "Inches", min: 0, max: 11, step: 1 },
    ],
  },
  {
    id: "weight",
    prompt: "Weight (lbs)",
    sectionId: "basicHealth",
    type: "number",
    min: 70,
    max: 500,
    required: true,
  },
  {
    id: "fruitsVeg",
    prompt: "How often do you include fruits and vegetables in your meals?",
    sectionId: "food",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.fruitsVeg,
  },
  {
    id: "processedFoods",
    prompt: "How often do you eat processed foods?",
    sectionId: "food",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.processedFoods,
  },
  {
    id: "sugarIntake",
    prompt: "How much added sugar do you typically consume?",
    sectionId: "food",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.sugarIntake,
  },
  {
    id: "homePreparedMeals",
    prompt: "How often do you eat meals prepared at home?",
    helperText: "Includes meals prepared by you, a family member, or someone in your household.",
    sectionId: "food",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.homePreparedMeals,
  },
  {
    id: "cardio",
    prompt: "How much cardio exercise do you do each week?",
    sectionId: "movement",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.cardio,
  },
  {
    id: "strengthTraining",
    prompt: "How often do you do strength training?",
    sectionId: "movement",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.strengthTraining,
  },
  {
    id: "dailyMovement",
    prompt: "How active are you during a typical day (not including workouts)?",
    sectionId: "movement",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.dailyMovement,
  },
  {
    id: "fitnessLevel",
    prompt: "How would you describe your overall physical fitness level?",
    sectionId: "movement",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.fitnessLevel,
  },
  {
    id: "sleepDuration",
    prompt: "How often do you get at least 7 hours of sleep?",
    sectionId: "sleep",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.sleepDuration,
  },
  {
    id: "sleepQuality",
    prompt: "How often do you have trouble falling or staying asleep?",
    sectionId: "sleep",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.sleepQuality,
  },
  {
    id: "sleepSchedule",
    prompt: "Do you maintain a consistent bedtime and wake time?",
    sectionId: "sleep",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.sleepSchedule,
  },
  {
    id: "timeWithOthers",
    prompt: "How often do you spend time with friends or family?",
    sectionId: "connection",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.timeWithOthers,
  },
  {
    id: "socialSupport",
    prompt: "How supportive is your social circle?",
    sectionId: "connection",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.socialSupport,
  },
  {
    id: "sharedMeals",
    prompt: "How often do you eat meals with other people?",
    sectionId: "connection",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.sharedMeals,
  },
  {
    id: "screenFreeMeals",
    prompt: "How often do you eat meals without screens (TV, phone, computer)?",
    sectionId: "connection",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.screenFreeMeals,
  },
  {
    id: "stressFrequency",
    prompt: "How often do you experience significant stress?",
    sectionId: "purposeStress",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.stressFrequency,
  },
  {
    id: "mentalHealthImpact",
    prompt: "How much does your mental health negatively impact your wellbeing?",
    sectionId: "purposeStress",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.mentalHealthImpact,
  },
  {
    id: "purpose",
    prompt: "Do you feel you have a clear sense of purpose in life?",
    sectionId: "purposeStress",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.purpose,
  },
  {
    id: "alcohol",
    prompt: "How many alcoholic drinks do you typically consume per week?",
    sectionId: "healthHabits",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.alcohol,
  },
  {
    id: "nicotine",
    prompt: "What best describes your nicotine use?",
    sectionId: "healthHabits",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.nicotine,
  },
  {
    id: "chronicDisease",
    prompt: "Do you currently have any chronic disease?",
    helperText: "Examples: heart disease, diabetes, cancer",
    sectionId: "healthHabits",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.chronicDisease,
  },
  {
    id: "selfRatedHealth",
    prompt: "How would you rate your overall health?",
    sectionId: "healthHabits",
    type: "singleSelect",
    required: true,
    options: OPTION_LABELS.selfRatedHealth,
  },
];

export const TOTAL_QUESTION_COUNT = ASSESSMENT_QUESTIONS.length;

export interface OptionalMarkerQuestion {
  id: OptionalMarkerKey;
  label: string;
  description?: string;
  options: AssessmentOption[];
}

const OPTIONAL_MARKER_OPTIONS: Record<OptionalMarkerKey, AssessmentOption[]> = {
  bloodPressure: [
    { value: "normal", label: "Normal" },
    { value: "elevated", label: "Elevated" },
    { value: "high", label: "High" },
    { value: "dontKnow", label: "I don’t know" },
  ],
  ldl: [
    { value: "optimal", label: "Optimal" },
    { value: "borderline", label: "Borderline" },
    { value: "high", label: "High" },
    { value: "dontKnow", label: "I don’t know" },
  ],
  fastingGlucose: [
    { value: "normal", label: "Normal" },
    { value: "prediabetes", label: "Prediabetes" },
    { value: "diabetes", label: "Diabetes" },
    { value: "dontKnow", label: "I don’t know" },
  ],
};

export const OPTIONAL_MARKER_QUESTIONS: OptionalMarkerQuestion[] = [
  {
    id: "bloodPressure",
    label: "Blood pressure",
    description: "Latest reading from a clinic or home cuff.",
    options: OPTIONAL_MARKER_OPTIONS.bloodPressure,
  },
  {
    id: "ldl",
    label: "LDL cholesterol",
    description: "From a fasting lipid panel.",
    options: OPTIONAL_MARKER_OPTIONS.ldl,
  },
  {
    id: "fastingGlucose",
    label: "Fasting blood glucose",
    description: "Bloodwork within the past year.",
    options: OPTIONAL_MARKER_OPTIONS.fastingGlucose,
  },
];
